#!/bin/bash  

# description: SSR_web Start Stop Restart  ,在服务器上注意要转成unix格式（set ff=unix）
# processname: 自定义ssr的service脚本 
# chkconfig: 234 20 80  
# 2345指脚本运行级别，234为文本界面，5为图形界面，60为脚本启动的次序号，20为脚本停止



# 开始
fun_start(){
	cd /usr/local/ssr/
	# 运行web
	python app.py >> ssr_web.log 2>&1 &
}
fun_stop(){
	# eval 用来执行这个打印出来的命令
	# 如 print iptables -L -nv
	# 控制台显示 iptables -L -nv 
	# 如果使用eval就会执行这个语句
	# 杀死app这个进程
	eval $(ps -ef | grep "[0-9] python app.py" | awk '{print "kill "$2}')
	# 杀死监听80端口的进程
	eval $(netstat -anp |grep ':80'| awk '{print($NF)}'| awk -F '/' '{print "kill -9 "$1}')
}



case $1 in  
	start)  
		fun_start
	;;   

	stop)     
		fun_stop
	;;   

	restart)  
		fun_stop
		fun_start
	;;
	status)
		result=netstat -anp |grep ':80'| awk '{print($NF)}'| awk -F '/' '{print $2}'
		if [ $result = 'python' ]
		then
			echo "This ssr_web is running"
		else
			echo "This ssr_web is stop"
		fi
	;;
esac
exit 0