#!/bin/bash  

# description: SSR_web Start Stop Restart  ,在服务器上注意要转成unix格式（set ff=unix）
# processname: 自定义ssr的service脚本 
# chkconfig: 234 20 80  
# 2345指脚本运行级别，234为文本界面，5为图形界面，60为脚本启动的次序号，20为脚本停止


SSR_HOME=/usr/local/ssr/shadowsocks
# 开始
fun_start(){
	# 启动ssr
	cd $SSR_HOME
	sh $SSR_HOME/run.sh 
}
fun_stop(){
	# 杀死ssr的所有启动经常
	cd $SSR_HOME
	sh $SSR_HOME/stop.sh 
}
case $1 in  
	start)  
		fun_start
	;;   

	stop)     
		fun_stop
	;;   

	restart)  
		fun_stop
		fun_start
	;;
esac
exit 0